development:
  adapter: postgresql
  encoding: unicode
  database: shouldi_development
  host: localhost
  pool: 5
  username: frost

test:
  adapter: postgresql
  encoding: unicode
  database: shouldi_test
  host: localhost
  pool: 5
  username: test

production:
  adapter: postgresql
  encoding: unicode
  database: shouldifollow
  host: localhost
  pool: 5
  username: shouldi
