development:
  adapter: postgresql
  encoding: unicode
  database: shouldi_development
  pool: 5
  username: frost
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: shouldi_test
  pool: 5
  username: test
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: shouldifollow
  pool: 5
  username: shouldi
  password:
