development:
  adapter: postgresql
  encoding: unicode
  database: shouldi_development
  host: localhost
  pool: 5
  username: <%= ENV['SHOULDIFOLLOW_DB_USER'] %>
  password: <%= ENV['SHOULDIFOLLOW_DB_PASSWORD'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: shouldi_test
  host: localhost
  pool: 5
  username: postgres
  password: <%= ENV['SHOULDIFOLLOW_DB_PASSWORD'] %>

production:
  adapter: postgresql
  encoding: unicode
  database: shouldifollow
  host: localhost
  pool: 5
  username: <%= ENV['SHOULDIFOLLOW_DB_USER'] %>
  password: <%= ENV['SHOULDIFOLLOW_DB_PASSWORD'] %>
